app_host: 127.0.0.1
app_port: 8000
auth_url: https://dev.try.direct/server/user/oauth_server/api/me
max_clients_number: 2
database:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: postgres
  database_name: stacker

amqp:
  host: ***REMOVED***
  port: 5672
  username: guest
  password: guest
