app_host: 0.0.0.0
app_port: 8000
auth_url: https://dev.try.direct/server/user/oauth_server/api/me
max_clients_number: 2

database:
  host: stackerdb
  port: 5432
  username: postgres
  password: postgres
  database_name: stacker

amqp:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

# Vault: address set here, token comes from VAULT_TOKEN env var (see docker-compose)
vault:
  address: http://37.139.9.187:8200
  token: change-me
  api_prefix: v1
  agent_path_prefix: agent
  ssh_key_path_prefix: users
